INSERT INTO room_tbl VALUES (1,'Standard Twin','STS_100_1.jpg','"위치 4층~6층 구성 침실1, 욕실1, 화장실1 침대 싱글Bed 2개 객실크기 32.9sqm(약 9.9평) 전망 Seaside View<br>"',null,null,'room');
INSERT INTO room_tbl VALUES (2,'Standard Double','SDS_100_1.jpg','"위치 4층~7층 구성 침실1, 욕실1, 화장실1 침대 더블Bed 1개 객실크기 32.9sqm(약 9.9평) 전망 Seaside View <br>"',null,null,'room');
INSERT INTO room_tbl VALUES (3,'Standard Super Twin','SSS_100_1.jpg','"위치 6층 구성 침실1, 욕실1, 화장실1 침대 더블Bed 1개+싱글Bed 1개 객실크기 32.9sqm(약 9.9평) 전망 Seaside View<br>"',null,null,'room');
INSERT INTO room_tbl VALUES (4,'Deluxe Twin (벙커룸)','DTS_100_1.jpg','"위치 8층 구성 침실1, 욕실1, 화장실1 침대 더블Bed 1개 + 싱글Bed 1개 객실크기 43.4sqm (약 13.1평) 전망 Seaside View<br>"',null,null,'room');
INSERT INTO room_tbl VALUES (5,'Deluxe Double','DDS_100_1.jpg','"위치 9층~11층 구성 침실1, 욕실1, 화장실1 침대 더블Bed 1개 객실크기 43.4sqm (약 13.1평) 전망 Seaside View<br>"',null,null,'room');
INSERT INTO room_tbl VALUES (6,'Deluxe Family','DFS_100_1.jpg','"위치 8층~11층 구성 침실1, 화장실1 침대 더블Bed 2개 객실크기 43.4sqm (약 13.1평) 전망 Seaside View<br>"',null,null,'room');
INSERT INTO room_tbl VALUES (7,'Studio Suite','SSU_100_1.jpg','"위치 10층, 11층 구성 침실1, 욕실1, 화장실1 침대 킹사이즈Bed 1개 객실크기 75.9sqm(약 23평) 전망 All Seaside View<br>"',null,null,'room');
INSERT INTO room_tbl VALUES (8,'Reed Suite','RSU_100_1.jpg','"위치 8층, 9층 구성 침실1, 욕실1, 화장실1 침대 킹사이즈Bed 1개 객실크기 75.9sqm(약 23평) 전망 All Seaside View<br>"',null,null,'room');
INSERT INTO room_tbl VALUES (9,'Panorama Suite','PSM_100_1.jpg','"위치 8층 구성 침실1, 욕실1, 화장실1 침대 킹사이즈Bed 1개 객실크기 119.4qm(약 36.1평) 전망 Parnorama view<br>"',null,null,'room');
INSERT INTO room_tbl VALUES (10,'Patio Suite','PSU_100_1.jpg','"위치 8층 구성 침실1, 욕실1, 화장실2 침대 킹사이즈Bed 1개 객실크기 119.4sqm(약 36.1평) 전망 Seaside View<br>"',null,null,'room');
